# Generated by Django 3.0.4 on 2020-03-12 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200312_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 12, 11, 6, 20, 734109)),
        ),
    ]
